# DockerFile for the Docker Compose
# Docker Compose is a tool for defining and running multi-container Docker applications.
# With Compose, you use a YAML file to configure your application’s services.
# Then, with a single command, you create and start all the services from your configuration.
# Here is an example of a Docker Compose file for the Dockerfile above:
#version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/mydatabase  # MongoDB connection string
    depends_on:
      - socket
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - my-network

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local