apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_HOST: mongodb-service
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cmFpX3VtZXJfZmFyb29x= # base64 for "admin"
  MONGO_INITDB_ROOT_PASSWORD: cmFpMTIz= # base64 for "password"