apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: socket-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: socket
  ports:
  - port: 4000
    targetPort: {{ .Values.socket.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: {{ .Values.mongodb.port }}