# DockerFile for the Socket Service
# This file is used to build the socket service image
# The image is built using the node image
# The image is built using the Dockerfile in the socket directory
# The image is built using the package.json file in the socket directory
# Use the node image
FROM node:18
# Set the working directory to /app

# Copy the package.json file to the working directory

# Install the dependencies

# Copy the rest of the files to the working directory

# Expose the port

# Run the app

# This Dockerfile is used to build the socket service image. It uses the node:14 image as
# the base image. It sets the working directory to /app and copies the package.json file to
# the working directory. It then installs the dependencies using npm install. It copies the
# rest of the files to the working directory and exposes the port 4000. Finally, it runs the
# app using node index.js.